version: "3.9"

services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    ports:
      - 8080:80
    # network_mode: host

  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    ports:
      - 4000:4000
    # network_mode: host


  # Database
  # db:
  #   image: mongo:latest
  #   container_name: "notificationdb"
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #     - MONGO_DB=notification
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
  #   volumes:
  #     - ./data/db:/data/db
  #   ports:
  #     - 27017:27017
